[package]
name = "eso-addon-manager"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/arviceblot/eso-addons"

[package.metadata.appimage]
auto_link = true
auto_link_exclude_list = [
    "libc.so*",
    "libdl.so*",
    "libpthread.so*",
]

[workspace]
members = [".", "cli", "core", "entity", "migration"]

[[bin]]
name = "eso-addon-manager"
path = "src/main.rs"

[dependencies]
eframe = "0.21.3"
tokio = { version = "1", features = ["full"] }
eso-addons-core = { path = "./core" }
strum = "0.24.1"
strum_macros = "0.24.3"
egui_file = "0.8.0"
itertools = "0.10.5"
