[package]
name = "eso-addons-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dirs = "4.0"
regex = "1"
scraper = "0.13.0"
tempfile = "3.1"
requestty = "0.3"
colored = "2"
prettytable-rs = "^0.8"
walkdir = "2"
toml = "0.5"
reqwest = { version = "0.11", features = ["gzip", "json"] }
zip = "0.6"
hostname = "^0.3"